twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        oauth_google_actif: '%env(default::OAUTH_GOOGLE_ID)%'

when@test:
    twig:
        strict_variables: true
